MODEL: 
  NAME: 'molo'
  BACKBONE: 'resnet50'          # ["resnet18", "resnet34", "resnet50"]
  SEED: 8
  USE_CLASSIFICATION: true
  USE_CLASSIFICATION_VALUE: 0.8
  USE_CONTRASTIVE: true
  USE_CONTRASTIVE_COFF: 0.05
  USE_RECONS: true 
  RECONS_COFF: 0.1
  USE_MOTION: true
  USE_LOCAL: false

TRAIN:
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 4
  TASKS_PER_BATCH: 4
  TRAIN_EPISODES: 75000
  VAL_FREQ: 5000
  
TEST:
  ONLY_TEST: false
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 2000
  TEST_MODEL_PATH: ''

DATA:
  DATASET: 'ssv2'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/home/zhangbin/tx/datasets/ssv2'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8
  NUM_CLASS: 64

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/ssv2_otam/1shot/molo'
  SAVE_FREQ: 75000

SOLVER:
  LR: 0.0001
  WEIGHT_DECAY: 5e-5
  OPTIM_METHOD: 'adam'   # ["adam", "sgd"]

