MODEL: 
  NAME: 'molo'
  BACKBONE: 'resnet18'          # ["resnet18", "resnet34", "resnet50"]
  SEED: 18
  USE_CLASSIFICATION: true
  USE_CLASSIFICATION_VALUE: 0.6
  USE_CONTRASTIVE: true
  USE_CONTRASTIVE_COFF: 0.05
  USE_RECONS: true 
  RECONS_COFF: 0.05
  USE_MOTION: true
  USE_LOCAL: false

TRAIN:
  WAY: 3
  SHOT: 1
  QUERY_PER_CLASS: 1
  TASKS_PER_BATCH: 16
  TRAIN_EPISODES: 6000
  VAL_FREQ: 100
  
TEST:
  ONLY_TEST: false
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 10000
  TEST_MODEL_PATH: ''

DATA:
  DATASET: 'ucf'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/home/deng/exp/datasets/'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8
  NUM_CLASS: 70

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/ucf/1shot/molo'
  SAVE_FREQ: 5000

SOLVER:
  OPTIM_METHOD: 'sgd'   # ["adam", "sgd"]

