MODEL: 
  NAME: 'trx'
<<<<<<< HEAD
  BACKBONE: 'resnet50'          # ["resnet18", "resnet34", "resnet50"]
=======
  BACKBONE: 'resnet34'          # ["resnet18", "resnet34", "resnet50"]
  SEED: 0
>>>>>>> FETCH_HEAD
  TEMP_SET: [2, 3]              # cardinalities e.g. 2,3 is pairs and triples
  TRANS_DROPOUT: 0.1            # Transformer dropout
  TRANS_LINEAR_OUT_DIM: 1152

TRAIN:
  WAY: 5
  SHOT: 1
<<<<<<< HEAD
  QUERY_PER_CLASS: 4

  TRAIN_EPISODES: 20010
  VAL_FREQ: 10000
=======
  QUERY_PER_CLASS: 1

  TRAIN_EPISODES: 20010
  VAL_FREQ: 200
>>>>>>> FETCH_HEAD
  
TEST:
  ONLY_TEST: false
  QUERY_PER_CLASS: 1
<<<<<<< HEAD
  TEST_EPISODES: 5000
  TEST_MODEL_PATH: 'checkpoint/ucf/1shot/trx/checkpoint_best.pt'

DATA:
  DATASET: 'ucf'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/home/zhangbin/tx/datasets/'
=======
  TEST_EPISODES: 10000
  TEST_MODEL_PATH: 'checkpoint/ssv2_otam/1shot/trx/checkpoint_best.pt'

DATA:
  DATASET: 'ucf'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/home/deng/exp/datasets/'
>>>>>>> FETCH_HEAD
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
<<<<<<< HEAD
  CHECKPOINT_DIR: 'checkpoint/ucf/1shot/trx'
  SAVE_FREQ: 10000

SOLVER:
  LR: 0.0001
=======
  CHECKPOINT_DIR: 'checkpoint/ssv2_ucf/1shot/trx'
  SAVE_FREQ: 10000

SOLVER:
>>>>>>> FETCH_HEAD
  OPTIM_METHOD: 'sgd'   # ["adam", "sgd"]

