INFO: ''
DEBUG: false
MODEL: 
  NAME: 'clipmei'
  BACKBONE: 'RN50'          # ["RN50", "ViT-B/16"]
  SEED: 6

TRAIN:
  WAY: 5
  SHOT: 5
  QUERY_PER_CLASS: 4

  TRAIN_EPISODES: 20010
  VAL_FREQ: 1000
  CLASS_NAME: ['Apply Eye Makeup', 'Archery', 'Baby Crawling', 'Balance Beam', 'Band Marching', 'Baseball Pitch', 'Basketball', 'Basketball Dunk', 'Bench Press', 'Biking', 'Billiards', 'Blow DryHair', 'Body Weight Squats', 'Bowling', 'Boxing Punching Bag', 'Boxing Speed Bag', 'Breast Stroke', 'Brushing Teeth', 'Cricket Bowling', 'Drumming', 'Fencing', 'Field Hockey Penalty', 'Frisbee Catch', 'Front Crawl', 'Haircut', 'Hammering', 'Head Massage', 'Hula Hoop', 'Javelin Throw', 'Juggling Balls', 'Jumping Jack', 'Kayaking', 'Knitting', 'Long Jump', 'Lunges', 'Military Parade', 'Mixing', 'Mopping Floor', 'Nunchucks', 'Parallel Bars', 'Pizza Tossing', 'Playing Cello', 'Playing Dhol', 'Playing Flute', 'Playing Piano', 'Playing Sitar', 'Playing Tabla', 'Playing Violin', 'Pole Vault', 'Pull Ups', 'Push Ups', 'Rafting', 'Rope Climbing', 'Rowing', 'Shaving Beard', 'Skijet', 'Soccer Juggling', 'Soccer Penalty', 'Sumo Wrestling', 'Swing', 'Table Tennis Shot', 'Tai Chi', 'Throw Discus', 'Trampoline Jumping', 'Typing', 'Uneven Bars', 'Walking WithDog', 'Wall Pushups', 'Writing On Board', 'Yo Yo']
  
TEST:
  ONLY_TEST: false
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 5000
  TEST_MODEL_PATH: 'checkpoint/ucf/5shot/clipmei/checkpoint_best.pt'
  CLASS_NAME: ['Blowing Candles', 'Clean And Jerk', 'Cliff Diving', 'Cutting in Kitchen', 'Diving', 'Floor Gymnastics', 'Golf Swing', 'Handstand Walking', 'Horse Race', 'Ice Dancing', 'Jump Rope', 'Pommel Horse', 'Punch', 'Rock Climbing Indoor', 'Salsa Spin', 'Skiing', 'Sky Diving', 'Still Rings', 'Surfing', 'Tennis Swing', 'Volleyball Spiking']
  
DATA:
  DATASET: 'ucf'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/root/datasets/'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/ucf/5shot/clipmei'
  SAVE_FREQ: 20000

SOLVER:
  LR: 0.00001
  WEIGHT_DECAY: 5e-5
  OPTIM_METHOD: 'adam'   # ["adam", "sgd"]

