MODEL: 
  NAME: 'strm'
  BACKBONE: 'resnet50'          # ["resnet18", "resnet34", "resnet50"]
  TEMP_SET: [2]              # cardinalities e.g. 2,3 is pairs and triples
  TRANS_DROPOUT: 0.1            # Transformer dropout
  TRANS_LINEAR_OUT_DIM: 1152

TRAIN:
  WAY: 5
  SHOT: 5
  QUERY_PER_CLASS: 4

  TRAIN_EPISODES: 75010
  VAL_FREQ: 10000
  
TEST:
  ONLY_TEST: false
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 10000
  TEST_MODEL_PATH: '/home/zhangbin/tx/FSAR/test_ckp/strm/checkpoint_ssv2_best.pt'

DATA:
  DATASET: 'ssv2'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/home/zhangbin/tx/datasets/ssv2'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/ssv2_otam/5shot/strm'
  SAVE_FREQ: 5000

SOLVER:
  OPTIM_METHOD: 'sgd'   # ["adam", "sgd"]

