MODEL: 
  NAME: 'strm'
  BACKBONE: 'resnet34'          # ["resnet18", "resnet34", "resnet50"]
  TEMP_SET: [2]              # cardinalities e.g. 2,3 is pairs and triples
  TRANS_DROPOUT: 0.1            # Transformer dropout
  TRANS_LINEAR_OUT_DIM: 1152

TRAIN:
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 1

  TRAIN_EPISODES: 20010
  VAL_FREQ: 200
  
TEST:
  ONLY_TEST: false
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 3000
  TEST_MODEL_PATH: ''

DATA:
  DATASET: 'ucf'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/home/deng/exp/datasets/'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/ucf/1shot/strm'
  SAVE_FREQ: 10000

SOLVER:
  OPTIM_METHOD: 'sgd'   # ["adam", "sgd"]

