MODEL: 
  NAME: 'ta2n'
  BACKBONE: 'resnet50'
  SEED: 111
  TIMEWISE: true
  DIST_NORM: false
  METRIC: 'cos'
  DROPOUT: 0.5
  TRANS_LINEAR_OUT_DIM: 1152

TRAIN:
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 5
  TRAIN_EPISODES: 75010
  VAL_FREQ: 5000

TEST:
  ONLY_TEST: true
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 10000
  TEST_MODEL_PATH: '/home/zhangbin/tx/FSAR/test_ckp/ta2n/ssv2_otam_1shot_last.pt'
DATA:
  DATASET: 'ssv2'
  DATA_DIR: '/home/zhangbin/tx/datasets/ssv2'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/ssv2_otam/1shot/ta2n'
  SAVE_FREQ: 5000
  RESUME_FROM_CHECKPOINT: false

SOLVER:
  OPTIM_METHOD: 'sgd'
