MODEL: 
  NAME: 'ta2n'
  BACKBONE: 'resnet50'
  TIMEWSIE: true
  DIST_NORM: false
  METRIC: 'cos'
  DROPOUT: 0.5

TRAIN:
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 5
  TRAINING_ITERATIONS: 75010
  VAL_FREQ: 200

TEST:
  ONLY_TEST: false
  QUERY_PER_CLASS_TEST: 1

DATA:
  DATASETS: 'ssv2'
  DATA_DIR: '/home/deng/exp/datasets/ssv2'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/ssv2_otam/1shot/ta2n/baseline_ta2n'
  SAVE_FREQ: 10000
  RESUME_FROM_CHECKPOINT: false

SOLVER:
  OPTIM_METHOD: 'sgd'
