MODEL: 
  NAME: 'ta2n'
  BACKBONE: 'resnet50'
  SEED: 10
  TIMEWISE: true
  DIST_NORM: false
  METRIC: 'cos'
  DROPOUT: 0.5
  TRANS_LINEAR_OUT_DIM: 1152

TRAIN:
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 5
  TRAIN_EPISODES: 20010
  VAL_FREQ: 2000

TEST:
  ONLY_TEST: false
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 3000
  TEST_MODEL_PATH: '/home/zhangbin/tx/FSAR/test_ckp/ta2n/checkpoint_ssv2_last.pt'
DATA:
  DATASET: 'ucf'
  DATA_DIR: '/home/zhangbin/tx/datasets/'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/ucf/1shot/ta2n'
  SAVE_FREQ: 10000
  RESUME_FROM_CHECKPOINT: false

SOLVER:
  OPTIM_METHOD: 'sgd'
