MODEL: 
  NAME: 'raw'
  BACKBONE: 'resnet50'          # ["resnet18", "resnet34", "resnet50"]
  SEED: 0

TRAIN:
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 4

  TRAIN_EPISODES: 75010
  VAL_FREQ: 5000
  
TEST:
  ONLY_TEST: true
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 10000
  #TEST_MODEL_PATH: '/home/zhangbin/tx/FSAR/test_ckp/raw/checkpoint_ssv2_best.pt'
  TEST_MODEL_PATH: 'checkpoint/ssv2_otam/1shot/raw/checkpoint_last.pt'

DATA:
  DATASET: 'ssv2'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/home/zhangbin/tx/datasets/ssv2'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/ssv2_otam/1shot/raw'
  SAVE_FREQ: 75000

SOLVER:
  LR: 0.001
  OPTIM_METHOD: 'sgd'   # ["adam", "sgd"]

