
MODEL:
  NAME: 'raw'
  BACKBONE: 'resnet50'          # ["resnet18", "resnet34", "resnet50"]
  SEED: 0

TRAIN:
  WAY: 5
  SHOT: 1
  QUERY_PER_CLASS: 4

  TRAIN_EPISODES: 20010
  VAL_FREQ: 20000

TEST:
  ONLY_TEST: false
  QUERY_PER_CLASS: 1
  TEST_EPISODES: 10000
  TEST_MODEL_PATH: '/home/zhangbin/tx/FSAR/test_ckp/raw/checkpoint_ucf.pt'
  #TEST_MODEL_PATH: '/home/zhangbin/tx/FSAR/checkpoint/ucf/1shot/strm/checkpoint_last.pt'

DATA:
  DATASET: 'ucf'   # ["ssv2", 'ssv2_cmn', "kinetics", "hmdb", "ucf"]
  DATA_DIR: '/home/zhangbin/tx/datasets/'
  SEQ_LEN: 8
  IMG_SIZE: 224
  NUM_WORKERS: 8

CHECKPOINT:
  CHECKPOINT_DIR: 'checkpoint/ucf/1shot/raw'
  SAVE_FREQ: 20000

SOLVER:
  LR: 0.0001
  OPTIM_METHOD: 'sgd'   # ["adam", "sgd"]